// <auto-generated />
using System;
using CMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260612073026_AddImageUrlToCategory")]
    partial class AddImageUrlToCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMS.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cập nhật xu hướng AI, IoT và lập trình.",
                            Name = "Tin tức Công nghệ"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kinh nghiệm phượt và các điểm đến hấp dẫn.",
                            Name = "Đời sống du lịch"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Các bài tập và chế độ ăn uống lành mạnh.",
                            Name = "Sức khỏe Thể thao"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Phương pháp học tập và kỹ năng mềm.",
                            Name = "Giáo dục Kỹ năng"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tài liệu ASP.NET Core và SQL Server.",
                            Name = "Góc lập trình viên"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Chia sẻ kinh nghiệm startup và kinh doanh online.",
                            Name = "Kinh doanh Khởi nghiệp"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Đánh giá các bộ phim bom tấn và series mới nhất.",
                            Name = "Review Phim Ảnh"
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.CategoryProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các sản phẩm áo thun cotton 100% thoáng mát, co giãn tốt.",
                            Name = "Áo thun Nam/Nữ"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Quần jeans nam nữ kiểu dáng hiện đại, chất denim dày dặn.",
                            Name = "Quần Jeans"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Đầm váy thiết kế, chất liệu nhẹ nhàng, sang trọng.",
                            Name = "Váy thời trang"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Áo khoác gió, hoodie, bomber phong cách trẻ trung.",
                            Name = "Áo khoác"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nón, túi xách, kính mát, vớ và các phụ kiện thời trang khác.",
                            Name = "Phụ kiện"
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Đường Ba Tháng Hai, Quận 10, TP.HCM",
                            Email = "khachhang@gmail.com",
                            FullName = "Nguyễn Văn Khách",
                            Password = "123",
                            Phone = "0908765432"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Lê Lợi, Quận 1, TP.HCM",
                            Email = "hoatran@gmail.com",
                            FullName = "Trần Thị Hoa",
                            Password = "hoa123",
                            Phone = "0912345678"
                        },
                        new
                        {
                            Id = 3,
                            Address = "78 Nguyễn Huệ, Quận 1, TP.HCM",
                            Email = "tuanle@gmail.com",
                            FullName = "Lê Minh Tuấn",
                            Password = "tuan456",
                            Phone = "0987654321"
                        },
                        new
                        {
                            Id = 4,
                            Address = "22 Trần Hưng Đạo, Quận 5, TP.HCM",
                            Email = "nganpham@gmail.com",
                            FullName = "Phạm Thu Ngân",
                            Password = "ngan789",
                            Phone = "0936789012"
                        },
                        new
                        {
                            Id = 5,
                            Address = "101 Điện Biên Phủ, Bình Thạnh, TP.HCM",
                            Email = "namvu@gmail.com",
                            FullName = "Vũ Hoàng Nam",
                            Password = "nam321",
                            Phone = "0971234567"
                        },
                        new
                        {
                            Id = 6,
                            Address = "1 Vùng Cấm, Chợ Lớn, TP.HCM",
                            Email = "longly@gmail.com",
                            FullName = "Lý Tiểu Long",
                            Password = "long123",
                            Phone = "0999888777"
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            Notes = "Giao giờ hành chính",
                            OrderDate = new DateTime(2026, 5, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 5, 22, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            Notes = "Gọi điện trước khi giao",
                            OrderDate = new DateTime(2026, 5, 28, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            Notes = "Giao buổi tối sau 18h",
                            OrderDate = new DateTime(2026, 6, 1, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 6, 3, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 5,
                            Notes = "Bọc kỹ hộp quà tặng",
                            OrderDate = new DateTime(2026, 6, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 6,
                            Notes = "Đóng gói cẩn thận",
                            OrderDate = new DateTime(2026, 6, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 2,
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 350000m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 9,
                            Quantity = 1,
                            UnitPrice = 290000m
                        },
                        new
                        {
                            Id = 4,
                            OrderId = 2,
                            ProductId = 14,
                            Quantity = 1,
                            UnitPrice = 320000m
                        },
                        new
                        {
                            Id = 5,
                            OrderId = 3,
                            ProductId = 14,
                            Quantity = 1,
                            UnitPrice = 320000m
                        },
                        new
                        {
                            Id = 6,
                            OrderId = 3,
                            ProductId = 7,
                            Quantity = 1,
                            UnitPrice = 420000m
                        },
                        new
                        {
                            Id = 7,
                            OrderId = 4,
                            ProductId = 11,
                            Quantity = 2,
                            UnitPrice = 320000m
                        },
                        new
                        {
                            Id = 8,
                            OrderId = 4,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 160000m
                        },
                        new
                        {
                            Id = 9,
                            OrderId = 5,
                            ProductId = 16,
                            Quantity = 1,
                            UnitPrice = 580000m
                        },
                        new
                        {
                            Id = 10,
                            OrderId = 6,
                            ProductId = 15,
                            Quantity = 1,
                            UnitPrice = 520000m
                        },
                        new
                        {
                            Id = 11,
                            OrderId = 6,
                            ProductId = 6,
                            Quantity = 2,
                            UnitPrice = 380000m
                        },
                        new
                        {
                            Id = 12,
                            OrderId = 7,
                            ProductId = 17,
                            Quantity = 1,
                            UnitPrice = 120000m
                        },
                        new
                        {
                            Id = 13,
                            OrderId = 7,
                            ProductId = 18,
                            Quantity = 1,
                            UnitPrice = 99000m
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            Content = "ASP.NET Core là framework mã nguồn mở của Microsoft, cho phép xây dựng ứng dụng web hiệu năng cao, đa nền tảng. Để bắt đầu học ASP.NET Core, bạn cần nắm vững C#, HTML/CSS/JavaScript cơ bản.\n\nBước 1: Học C# từ cơ bản đến nâng cao (OOP, LINQ, async/await)\nBước 2: Tìm hiểu về HTTP, REST API và web fundamentals\nBước 3: Bắt đầu với ASP.NET Core MVC - tìm hiểu về Controller, View, Model\nBước 4: Học Entity Framework Core để thao tác với database\nBước 5: Thực hành xây dựng dự án thực tế như CMS, Shop, Blog...\n\nHãy thực hành đều đặn mỗi ngày, tham gia cộng đồng lập trình viên và không ngại đặt câu hỏi khi gặp khó khăn. Chúc bạn thành công!",
                            CreatedDate = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=600",
                            Title = "Lộ trình học ASP.NET Core từ A đến Z"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Content = "Mùa hè 2026 đang đến gần, đây là thời điểm lý tưởng để khám phá những bãi biển tuyệt đẹp trải dài từ Bắc vào Nam của Việt Nam.\n\n1. Phú Quốc - 'Đảo Ngọc' với nước biển trong xanh, bãi cát trắng mịn\n2. Đà Nẵng - Bãi biển Mỹ Khê được tạp chí Forbes bình chọn là một trong những bãi biển đẹp nhất hành tinh\n3. Nha Trang - Thiên đường nghỉ dưỡng với vịnh biển hình bán nguyệt\n4. Hội An - Cửa Đại với vẻ đẹp bình yên, làng quê yên ả\n5. Phan Thiết - Mũi Né với đồi cát bay đặc trưng độc đáo\n6. Quy Nhơn - Eo Gió với vẻ hoang sơ và sóng biển hùng vĩ\n7. Vũng Tàu - Điểm du lịch cuối tuần lý tưởng của người Sài Gòn\n\nDù bạn đi bất kỳ bãi biển nào, hãy nhớ bảo vệ môi trường và không xả rác xuống biển nhé!",
                            CreatedDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=600",
                            Title = "Top 7 bãi biển đẹp nhất Việt Nam hè 2026"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Content = "Chạy bộ là một trong những bài tập thể dục đơn giản, hiệu quả và tiết kiệm chi phí nhất. Với kế hoạch tập luyện đúng đắn, bạn hoàn toàn có thể giảm 5kg trong vòng 1 tháng.\n\nKế hoạch tập:\n- Tuần 1: Chạy nhẹ 20-30 phút, tốc độ 6-7 km/h, 3 buổi/tuần\n- Tuần 2: Tăng lên 35-40 phút, thêm 1 buổi, tốc độ 7-8 km/h\n- Tuần 3: Chạy interval (1 phút nhanh + 2 phút chậm), 4-5 buổi/tuần\n- Tuần 4: Chạy dài 45-50 phút liên tục, kết hợp uphill\n\nMẹo quan trọng: Uống đủ nước, ăn nhẹ trước tập 1-2 tiếng, mang giày chuyên dụng, và quan trọng nhất là kiên trì! Đừng bỏ cuộc sau 1-2 tuần khi chưa thấy kết quả.",
                            CreatedDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?q=80&w=600",
                            Title = "5 bài tập chạy bộ giúp bạn giảm 5kg trong 1 tháng"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Content = "Trí tuệ nhân tạo (AI) đang len lỏi vào mọi ngành nghề, và thời trang cũng không ngoại lệ. Từ thiết kế đến bán lẻ, AI đang cách mạng hóa cách chúng ta mua sắm và mặc đẹp.\n\nCác ứng dụng AI trong thời trang:\n1. Gợi ý phong cách cá nhân: Các ứng dụng như Stitch Fix dùng AI để phân tích sở thích và đề xuất trang phục phù hợp\n2. Thử đồ ảo (Virtual Try-On): AR + AI cho phép thử quần áo ngay trên điện thoại\n3. Dự đoán xu hướng: AI phân tích dữ liệu mạng xã hội để dự báo trend mùa tới\n4. Tối ưu chuỗi cung ứng: AI giúp quản lý tồn kho và giảm lãng phí sản xuất\n5. Thiết kế AI: Các model AI như DALL-E có thể tạo ra những mẫu thiết kế độc đáo\n\nThời trang AI không phải là tương lai xa vời - nó đang diễn ra ngay hôm nay!",
                            CreatedDate = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?q=80&w=600",
                            Title = "AI đang thay đổi ngành thời trang như thế nào?"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Content = "Làm việc nhóm là kỹ năng không thể thiếu trong môi trường công nghệ. Hầu hết các dự án phần mềm đều yêu cầu sự phối hợp của nhiều người, từ lập trình viên, designer đến tester.\n\nCác nguyên tắc vàng khi làm việc nhóm:\n1. Phân chia công việc rõ ràng: Dùng Trello, Jira, hoặc GitHub Projects để assign task\n2. Giao tiếp thường xuyên: Daily standup ngắn 15 phút để sync tiến độ\n3. Code review lẫn nhau: Không có code nào hoàn hảo ngay lần đầu\n4. Sử dụng Git flow: Branch riêng cho từng feature, merge request có review\n5. Tôn trọng ý kiến: Tranh luận về code, không tranh luận về cái tôi\n6. Document đầy đủ: README.md, API docs, comment code rõ ràng\n\nKỹ năng teamwork tốt sẽ là lợi thế lớn khi bạn đi phỏng vấn tại các công ty công nghệ!",
                            CreatedDate = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=600",
                            Title = "Kỹ năng Teamwork hiệu quả trong nhóm đồ án CNTT"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Content = "Athleisure - phong cách kết hợp giữa thể thao (athletic) và thời thượng (leisure) - đang là xu hướng thống trị thời trang 2026. Không chỉ mặc tập gym, quần áo thể thao giờ đây xuất hiện khắp mọi nơi từ văn phòng đến tiệc cocktail.\n\nĐặc trưng của Athleisure:\n- Chất liệu: Vải co giãn 4 chiều, thấm hút mồ hôi, chống nhăn\n- Màu sắc: Earth tone (nâu đất, be, khaki), monochrome, pastel\n- Item must-have: Legging, jogger, hoodie oversized, sneakers white\n- Brand nổi bật: Nike, Adidas, Lululemon, Vuori\n\nCách phối đồ Athleisure đi làm:\n- Legging đen + blazer trắng + sneakers trắng\n- Jogger kaki + áo thun trắng tucked-in + loafer\n- Sports bra + high-waist shorts + oversized jacket\n\nAthleisure là lựa chọn hoàn hảo cho nhịp sống bận rộn ngày nay!",
                            CreatedDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=600",
                            Title = "Xu hướng thời trang thể thao Athleisure 2026"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            Content = "Khởi nghiệp chưa bao giờ là con đường dễ dàng. Dưới đây là 5 bài học xương máu từ những founder đã từng thất bại và làm lại từ đầu: 1. Đừng làm sản phẩm không ai cần. 2. Quản lý dòng tiền chặt chẽ. 3. Tuyển đúng người. 4. Lắng nghe khách hàng. 5. Kiên trì nhưng biết điểm dừng.",
                            CreatedDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1556761175-5972d5ce14ef?q=80&w=600",
                            Title = "5 Bài Học Đắt Giá Khi Lần Đầu Khởi Nghiệp"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            Content = "Dune mang đến một trải nghiệm thị giác và thính giác tuyệt đỉnh. Kỹ xảo hoành tráng, âm nhạc hùng hồn của Hans Zimmer, cùng diễn xuất xuất thần của dàn cast khiến bộ phim này trở thành một trong những tác phẩm khoa học viễn tưởng vĩ đại nhất thập kỷ.",
                            CreatedDate = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=600",
                            Title = "Review: Dune: Hành Tinh Cát - Siêu phẩm không thể bỏ lỡ"
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryProductId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryProductId = 1,
                            Description = "Áo thun cơ bản màu trắng, form regular fit, chất cotton 100% thoáng mát, thích hợp mặc mọi dịp.",
                            ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=400",
                            Name = "Áo Thun Cotton Basic Trắng",
                            Price = 150000m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryProductId = 1,
                            Description = "Áo thun polo cổ bẻ màu xanh navy lịch sự, chất pique cotton, phù hợp đi học, đi làm, dạo phố.",
                            ImageUrl = "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?q=80&w=400",
                            Name = "Áo Thun Polo Premium Navy",
                            Price = 220000m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryProductId = 1,
                            Description = "Áo thun in hình streetwear phong cách, chất cotton mềm mịn, form oversized trendy.",
                            ImageUrl = "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?q=80&w=400",
                            Name = "Áo Thun Graphic Streetwear",
                            Price = 180000m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 4,
                            CategoryProductId = 1,
                            Description = "Áo thun crop top nữ xinh xắn, dễ phối đồ, phong cách Hàn Quốc tươi trẻ.",
                            ImageUrl = "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=400",
                            Name = "Áo Thun Crop Top Nữ",
                            Price = 160000m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 5,
                            CategoryProductId = 2,
                            Description = "Quần jeans slimfit màu xanh denim cổ điển, co giãn nhẹ, ôm dáng tôn vóc dáng.",
                            ImageUrl = "https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=400",
                            Name = "Quần Jeans Slimfit Xanh",
                            Price = 350000m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 6,
                            CategoryProductId = 2,
                            Description = "Quần jeans skinny màu đen cá tính, co giãn 4 chiều, thoải mái khi vận động.",
                            ImageUrl = "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?q=80&w=400",
                            Name = "Quần Jeans Skinny Đen",
                            Price = 380000m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 7,
                            CategoryProductId = 2,
                            Description = "Quần jean baggy form rộng unisex phong cách Y2K đang thịnh hành, nam nữ đều mặc được.",
                            ImageUrl = "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?q=80&w=400",
                            Name = "Quần Jean Baggy Unisex",
                            Price = 420000m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 8,
                            CategoryProductId = 2,
                            Description = "Quần jean rách gối phong cách cá tính, wash màu nhạt, kết hợp dễ dàng với áo thun.",
                            ImageUrl = "https://images.unsplash.com/photo-1565084888279-aca607ecce0c?q=80&w=400",
                            Name = "Quần Jean Rách Gối Trendy",
                            Price = 390000m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 9,
                            CategoryProductId = 3,
                            Description = "Đầm voan hoa nhí dịu dàng phong cách vintage, phù hợp đi chơi, picnic, dạo phố.",
                            ImageUrl = "https://images.unsplash.com/photo-1495385794356-15371f348c31?q=80&w=400",
                            Name = "Váy Hoa Nhí Vintage",
                            Price = 290000m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 10,
                            CategoryProductId = 3,
                            Description = "Đầm ôm body tôn dáng, chất liệu satin cao cấp, thích hợp dự tiệc, sự kiện sang trọng.",
                            ImageUrl = "https://images.unsplash.com/photo-1566479179817-b359d2ee0f57?q=80&w=400",
                            Name = "Đầm Dạ Hội Sang Trọng",
                            Price = 650000m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 11,
                            CategoryProductId = 3,
                            Description = "Váy midi kẻ sọc thanh lịch, dài qua gối, phù hợp đi làm và đi chơi.",
                            ImageUrl = "https://images.unsplash.com/photo-1568252542512-9fe8fe9f6e1a?q=80&w=400",
                            Name = "Váy Midi Kẻ Sọc",
                            Price = 320000m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 12,
                            CategoryProductId = 3,
                            Description = "Chân váy xòe phong cách lolita đáng yêu, nhiều màu pastel, kết hợp với áo tuck-in.",
                            ImageUrl = "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?q=80&w=400",
                            Name = "Chân Váy Xòe Lolita",
                            Price = 280000m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 13,
                            CategoryProductId = 4,
                            Description = "Áo khoác bomber chất kaki cao cấp, 2 lớp giữ ấm, phong cách quân đội trendy.",
                            ImageUrl = "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=400",
                            Name = "Áo Khoác Bomber Kaki",
                            Price = 450000m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 14,
                            CategoryProductId = 4,
                            Description = "Áo hoodie nỉ bông ấm áp, form rộng unisex, có túi kangaroo và mũ che đầu.",
                            ImageUrl = "https://images.unsplash.com/photo-1556821840-3a63f15732ce?q=80&w=400",
                            Name = "Áo Khoác Hoodie Unisex",
                            Price = 320000m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 15,
                            CategoryProductId = 4,
                            Description = "Áo khoác gió chống nước nhẹ, có thể gấp lại bỏ túi, phù hợp du lịch, leo núi.",
                            ImageUrl = "https://images.unsplash.com/photo-1604644401890-0bd678c83788?q=80&w=400",
                            Name = "Áo Khoác Gió Chống Nước",
                            Price = 520000m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 16,
                            CategoryProductId = 4,
                            Description = "Áo blazer kẻ caro thanh lịch, oversize nhẹ, phù hợp đi làm, hội thảo, meeting.",
                            ImageUrl = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400",
                            Name = "Áo Blazer Lịch Sự",
                            Price = 580000m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 17,
                            CategoryProductId = 5,
                            Description = "Nón lưỡi trai chất kaki bền đẹp, thêu chữ phong cách streetwear.",
                            ImageUrl = "https://images.unsplash.com/photo-1521369909029-2afed882ba54?q=80&w=400",
                            Name = "Nón Lưỡi Trai Thêu Chữ",
                            Price = 120000m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 18,
                            CategoryProductId = 5,
                            Description = "Túi tote vải canvas cỡ lớn, đựng vừa laptop 14 inch, tiện dụng cho dân văn phòng và sinh viên.",
                            ImageUrl = "https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=400",
                            Name = "Túi Tote Canvas Basic",
                            Price = 99000m,
                            StockQuantity = 80
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Quản trị viên hệ thống",
                            PasswordHash = "123456",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Nguyễn Cao Đạt",
                            PasswordHash = "dat1969",
                            Role = "Editor",
                            Username = "dat_gv"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Nguyễn Văn A",
                            PasswordHash = "student1",
                            Role = "User",
                            Username = "sv_01"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Trần Thị B",
                            PasswordHash = "student2",
                            Role = "User",
                            Username = "sv_02"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Lê Văn C",
                            PasswordHash = "mod789",
                            Role = "Moderator",
                            Username = "moderator"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Phạm Thị Marketing",
                            PasswordHash = "mkt123",
                            Role = "Editor",
                            Username = "marketing_01"
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.CategoryProduct", b =>
                {
                    b.HasOne("CMS.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CMS.Data.Entities.Order", b =>
                {
                    b.HasOne("CMS.Data.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CMS.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("CMS.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMS.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CMS.Data.Entities.Post", b =>
                {
                    b.HasOne("CMS.Data.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CMS.Data.Entities.Product", b =>
                {
                    b.HasOne("CMS.Data.Entities.CategoryProduct", "CategoryProduct")
                        .WithMany("Products")
                        .HasForeignKey("CategoryProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryProduct");
                });

            modelBuilder.Entity("CMS.Data.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("CMS.Data.Entities.CategoryProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CMS.Data.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CMS.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
