// <auto-generated />
using System;
using CMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260604064800_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMS.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cập nhật xu hướng AI, IoT và lập trình.",
                            Name = "Tin tức Công nghệ"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kinh nghiệm phượt và các điểm đến hấp dẫn.",
                            Name = "Đời sống du lịch"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Các bài tập và chế độ ăn uống lành mạnh.",
                            Name = "Sức khỏe Thể thao"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Phương pháp học tập và kỹ năng mềm .",
                            Name = "Giáo dục Kỹ năng"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tài liệu ASP.NET Core và SQL Server.",
                            Name = "Góc lập trình viên"
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.CategoryProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các sản phẩm áo thun cotton 100% thoáng mát, co giãn tốt.",
                            Name = "Áo thun Nam/Nữ"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Quần jeans nam nữ kiểu dáng hiện đại, chất denim dày dặn.",
                            Name = "Quần Jeans"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Đầm váy thiết kế, chất liệu nhẹ nhàng, sang trọng.",
                            Name = "Váy thời trang"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Áo khoác gió, hoodie, bomber phong cách trẻ trung.",
                            Name = "Áo khoác"
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Đường Ba Tháng Hai, Quận 10, TP.HCM",
                            Email = "khachhang@gmail.com",
                            FullName = "Nguyễn Văn Khách",
                            Password = "123",
                            Phone = "0908765432"
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CMS.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CMS.Data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            Content = "Hướng dẫn chi tiết cho người mới bắt đầu...",
                            CreatedDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/img/dotnet.jpg",
                            Title = "Lộ trình học ASP.NET"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Content = "Những địa điểm không thể bỏ qua mùa hè này...",
                            CreatedDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/img/beach.jpg",
                            Title = "Top 5 bãi biển đẹp"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Content = "Lợi ích tuyệt vời của việc chạy bộ mỗi sáng...",
                            CreatedDate = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/img/run.jpg",
                            Title = "Chạy bộ đúng cách"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Content = "Trí tuệ nhân tạo đang thay đổi cuộc sống...",
                            CreatedDate = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/img/ai.jpg",
                            Title = "AI và tương lai"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Content = "Cách phối hợp hiệu quả trong nhóm đồ án...",
                            CreatedDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/img/team.jpg",
                            Title = "Kỹ năng Teamwork"
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryProductId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryProductId = 1,
                            Description = "Áo thun cơ bản, form rộng, vải cotton co giãn 4 chiều mềm mịn.",
                            ImageUrl = "/uploads/aothun1.jpg",
                            Name = "Áo Thun Cotton Basic",
                            Price = 150000m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            CategoryProductId = 1,
                            Description = "Áo thun polo cổ bẻ lịch sự, phù hợp đi học, đi làm, dạo phố.",
                            ImageUrl = "/uploads/aothun2.jpg",
                            Name = "Áo Thun Polo Premium",
                            Price = 220000m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            CategoryProductId = 2,
                            Description = "Quần jeans ống ôm nhẹ, màu xanh truyền thống trẻ trung.",
                            ImageUrl = "/uploads/jean1.jpg",
                            Name = "Quần Jeans Slimfit Blue",
                            Price = 350000m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 4,
                            CategoryProductId = 2,
                            Description = "Quần jeans ôm dáng skinny màu đen cá tính, co giãn thoải mái.",
                            ImageUrl = "/uploads/jean2.jpg",
                            Name = "Quần Jeans Skinny Black",
                            Price = 380000m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 5,
                            CategoryProductId = 3,
                            Description = "Đầm voan hoa nhí dịu dàng, phong cách vintage thanh lịch.",
                            ImageUrl = "/uploads/vay1.jpg",
                            Name = "Váy Hoa Nhí Vintage",
                            Price = 290000m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 6,
                            CategoryProductId = 3,
                            Description = "Đầm ôm body tôn dáng, thích hợp cho các buổi tiệc tối sang trọng.",
                            ImageUrl = "/uploads/vay2.jpg",
                            Name = "Đầm Dạ Hội Sang Trọng",
                            Price = 650000m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 7,
                            CategoryProductId = 4,
                            Description = "Áo khoác bomber chất kaki cao cấp, 2 lớp giữ ấm tốt.",
                            ImageUrl = "/uploads/khoak1.jpg",
                            Name = "Áo Khoác Bomber Kaki",
                            Price = 450000m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 8,
                            CategoryProductId = 4,
                            Description = "Áo hoodie nỉ bông ấm áp, form rộng unisex nam nữ đều mặc được.",
                            ImageUrl = "/uploads/khoak2.jpg",
                            Name = "Áo Khoác Hoodie Unisex",
                            Price = 320000m,
                            StockQuantity = 35
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Quản trị viên hệ thống",
                            PasswordHash = "123456",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Nguyễn Cao Thái",
                            PasswordHash = "thai1969",
                            Role = "Editor",
                            Username = "thai_gv"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Nguyễn Văn A",
                            PasswordHash = "student1",
                            Role = "User",
                            Username = "sv_01"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Trần Thị B",
                            PasswordHash = "student2",
                            Role = "User",
                            Username = "sv_02"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Lê Văn C",
                            PasswordHash = "mod789",
                            Role = "Moderator",
                            Username = "moderator"
                        });
                });

            modelBuilder.Entity("CMS.Data.Entities.CategoryProduct", b =>
                {
                    b.HasOne("CMS.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CMS.Data.Entities.Order", b =>
                {
                    b.HasOne("CMS.Data.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CMS.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("CMS.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMS.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CMS.Data.Entities.Post", b =>
                {
                    b.HasOne("CMS.Data.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CMS.Data.Entities.Product", b =>
                {
                    b.HasOne("CMS.Data.Entities.CategoryProduct", "CategoryProduct")
                        .WithMany("Products")
                        .HasForeignKey("CategoryProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryProduct");
                });

            modelBuilder.Entity("CMS.Data.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("CMS.Data.Entities.CategoryProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CMS.Data.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CMS.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
